name = "sercrow-api"
main = "dist/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "sercrow-api"

[vars]
NODE_ENV = "production"

# Add your environment variables here
# GOOGLE_SEARCH_API_KEY = "your-api-key"
# GOOGLE_SEARCH_ENGINE_ID = "your-engine-id"
# DATABASE_URL = "your-database-url"
# SESSION_SECRET = "your-session-secret"
# VITE_AUTH0_DOMAIN = "your-auth0-domain"
# VITE_AUTH0_CLIENT_ID = "your-auth0-client-id"
# VITE_AUTH0_AUDIENCE = "your-auth0-audience"

pages_build_output_dir = "dist"