name = "sercrow"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
pages_build_output_dir = "dist"

[env.production]
name = "sercrow-frontend"

[vars]
NODE_ENV = "production"
VITE_APP_NAME = "SerCrow"
VITE_APP_DESCRIPTION = "Private Search Engine with Built-in Browser"
